version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/zatubako'
      - '/zatubako/node_modules'
    ports:
      - '8080:8080'
